/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Boundary;

import ReglasNegocio.Control.*;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author nobls
 */
public class VentanaLogin extends javax.swing.JFrame {
    private int prueba = 0;
    public static int idUsuario=-1;
    public static String datos="brandon";
    private final JFrame estaVentana = this;
    private ControlInicioSesion verificardatosinicio = new ControlInicioSesion();
    
    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        super("Iniciar Sesión");
        MostrarFormularioInicioSesion();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIconoEmpresa = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        labelUsuario1 = new javax.swing.JLabel();
        fieldContra = new javax.swing.JPasswordField();
        botonLogin = new javax.swing.JButton();
        textUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelIconoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prestamilIcono.png"))); // NOI18N

        labelContraseña.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        labelContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contra.png"))); // NOI18N
        labelContraseña.setText("Contraseña");

        labelUsuario1.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        labelUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        labelUsuario1.setText("Usuario");

        fieldContra.setText("jPasswordField1");
        fieldContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContraActionPerformed(evt);
            }
        });

        botonLogin.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        botonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        botonLogin.setText("Iniciar Sesión");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(labelIconoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelContraseña)
                            .addComponent(labelUsuario1)
                            .addComponent(fieldContra, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(textUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(botonLogin)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelIconoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldContra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        //Obtenemos los textos y lo enviamos a la función del login
        
          String  usuarioTemp = textUsuario.getText();
          String contraseñaTemp = fieldContra.getText();
           prueba= verificardatosinicio.verificarDatosInicio(usuarioTemp,contraseñaTemp);
        
        //Se lo mandamos a la función EnviarDatosUsuario
        //Si es verdadero manda a llamar a la ventana de Home
        if(prueba !=-1){    
            idUsuario=prueba;
            System.out.println(idUsuario);
             this.dispose();
            new VentanaPrincipal();
        }else{
            //Mandamos a mostrar la alerta de datos incorrectos
            MostrarErrorDatosIncorrectos();
            
            /*Limpiamos los fields*
            usuarioTemp = textUsuario.setText("");
            contraseñaTemp = fieldContra.setText("");*/
            
        }
    }//GEN-LAST:event_botonLoginActionPerformed

    private void fieldContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContraActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    private void MostrarFormularioInicioSesion() {
       initComponents();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JPasswordField fieldContra;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelIconoEmpresa;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

    private void MostrarErrorDatosIncorrectos() {
        String textoError = "¡Error! El usuario y/o la contraseña estan erroneos, verifique sus datos";

        JOptionPane alertaError = new JOptionPane(textoError, JOptionPane.ERROR_MESSAGE);
        JDialog modalAlerta = alertaError.createDialog("Datos Incorrectos");
        modalAlerta.setAlwaysOnTop(true);
        modalAlerta.setVisible(true);
    }




}
