/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion.Boundary;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author nobls
 */
public class VentanaCreditosTabla extends javax.swing.JDialog {
    /**
     * Creates new form VentanaCreditosTabla
     */
    public VentanaCreditosTabla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setVisible(true);
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCreditos = new javax.swing.JPanel();
        labelTipoCreditos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCreditos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCreditos.setBackground(new java.awt.Color(0, 0, 0));

        labelTipoCreditos.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        labelTipoCreditos.setForeground(new java.awt.Color(255, 255, 255));
        labelTipoCreditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipoCreditos.setText("TIPO DE CREDITOS");

        javax.swing.GroupLayout panelCreditosLayout = new javax.swing.GroupLayout(panelCreditos);
        panelCreditos.setLayout(panelCreditosLayout);
        panelCreditosLayout.setHorizontalGroup(
            panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreditosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTipoCreditos)
                .addGap(302, 302, 302))
        );
        panelCreditosLayout.setVerticalGroup(
            panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTipoCreditos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaCreditos.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        tablaCreditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Diario (25 dias)", "$60", "$120", "$180", "$$240", "$300", "N/A", "N/A", "N/A", "N/A", "N/A"},
                {"Semanal (8 semanas)", "N/A", "N/A", "$562.50", "$637.50", "$912.50", "$937.50", "$1,262.50", "$1,237.50", "$1,387.50", "$1,537.50"},
                {"Semanal (12 semanas)", "N/A", "N/A", "$425", "$625", "$691.50", "$658.50", "$958.50", "$891.70", "$1,000", "$1,108.30"},
                {"Semanal (16 semanas)", "N/A", "N/A", "$360", "$469", "$582", "$694", "$806.50", "$718.80", "$806.30", "$893.80"},
                {"Semanal (20 semanas)", "N/A", "N/A", "$315", "$415", "$515", "$615", "$715", "$615", "$690", "$765"},
                {"Quincenal (4 quincenas)", "N/A", "N/A", "$1,215", "$1,475", "$1,825", "$1,575", "$2,525", "$2,875", "$2,325", "$3,075"},
                {"Quincenal (6 quincenas)", "N/A", "N/A", "$850", "$1,117", "$1,383", "$1,050", "$1,917", "$2,183", "$2,450", "$2,217"},
                {"Quincenal (8 quincenas)", "N/A", "N/A", "$713", "$813", "$1,663", "$1,013", "$1,513", "$1,838", "$2,063", "$1,788"},
                {"Mensual (1 mes)", "$1,200", "$2,400", "$3,600", "$4,800", "$6,000", "$7,200", "$8,400", "$10,600", "$10,800", "$11,000"},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Modalidad", "$1,000", "$2,000", "$3,000", "$4,000", "$5,000", "$6,000", "$7,000", "$8,000", "$9,000", "$10,000"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCreditos);
        if (tablaCreditos.getColumnModel().getColumnCount() > 0) {
            tablaCreditos.getColumnModel().getColumn(0).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(0).setPreferredWidth(200);
            tablaCreditos.getColumnModel().getColumn(1).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(2).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(3).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(4).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(5).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(6).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(7).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(8).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(9).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCreditosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCreditosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCreditosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCreditosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCreditosTabla dialog = new VentanaCreditosTabla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTipoCreditos;
    private javax.swing.JPanel panelCreditos;
    private javax.swing.JTable tablaCreditos;
    // End of variables declaration//GEN-END:variables
}
